# Generated By: Claude Code (Claude Opus 4.7)
# Makefile for claude-skill-review.
#
# This repo contains a Claude Code skill (SKILL.md plus helper scripts and
# JSON schemas). It is not an installable Python package, so install/uninstall/
# coverage/typecheck/complexity/mutation targets from the standard Python
# Makefile are not applicable. Modeled on the Documentation-Only Projects
# template in ~/source/standards/build/makefile.md, extended with test/format/
# lint for the Python scripts under scripts/.

.PHONY: all check help install-dev format format-check lint test

PYTHON ?= python

all: check

check: format-check lint test  ## Run format-check, lint, and test (default)

.DEFAULT_GOAL := check

help:  ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

install-dev:  ## Install dev dependencies (pytest, jsonschema, black, flake8)
	$(PYTHON) -m pip install --quiet -e '.[dev]'

format: install-dev  ## Format Python with black
	$(PYTHON) -m black scripts tests

format-check: install-dev  ## Check Python formatting (exits non-zero on diffs)
	$(PYTHON) -m black --check scripts tests

lint: install-dev  ## Lint Python with flake8
	$(PYTHON) -m flake8 --max-line-length=88 --extend-ignore=E203,W503 scripts tests

test: install-dev  ## Run pytest test suite (includes bash-script tests via subprocess)
	$(PYTHON) -m pytest
