#!/usr/bin/env bash
# Generated By: Claude Code (Claude Opus 4.7)
# Bootstrap the .tmp-review-findings/ workspace at the project root.
#
# Idempotent: safe to run on every invocation of the review skill.
# Honors PROJECT_ROOT env var when set (used by tests); defaults to PWD.

set -euo pipefail

ROOT="${PROJECT_ROOT:-$PWD}"
WORK_DIR="$ROOT/.tmp-review-findings"

mkdir -p "$WORK_DIR/raw" 
mkdir -p "$WORK_DIR/validation"

# Always write the .gitignore as a bare '*' with no trailing newline.
# Idempotent because the content is fixed and short.
printf '*' > "$WORK_DIR/.gitignore"

echo "bootstrap: $WORK_DIR ready"
